apiVersion: myapp.spike.com/v1
kind: Buyer
metadata:
  labels:
    app.kubernetes.io/name: buyer
    app.kubernetes.io/instance: buyer-sample
    app.kubernetes.io/part-of: k8s-spike-v2
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-spike-v2
  name: buyer-sample
spec:
  # TODO(user): Add fields here
